### ISSUE TITLE
sed and date issues on OS X

### ISSUE THREAD

**Issue by thejmazz** [weakish/gister#14]
Seems `/usr/bin/sed` on my Mac is not up to par:
<img width="984" alt="screen shot 2015-11-25 at 4 34 04 pm" src="https://cloud.githubusercontent.com/assets/1270998/11410072/7a4915b0-9392-11e5-8e18-e4134584a00c.png">

I tried

```bash
$ brew install gnu-sed
$ echo alias sed=gsed >> ~/.bashrc
```
and sourced. Same error. Then I did

```bash
$ sudo vim `which gister`
:%s/sed/gsed/g
:wq
```

and now it works :). Not sure why aliasing didn't do the trick though.

**Comment by thejmazz** [comment]
Also, need `gdate` instead of `date`. You can get `gdate` with

```bash
brew install coreutils
```

Change line 222 or search for the line with `$last_updated_unixtime`.

**Comment by weakish** [comment]
>     $ echo alias sed=gsed >> ~/.bashrc
>  ...
> Not sure why aliasing didn't do the trick though.

By default only interactive bash shell reads `~/.bashrc`.

Thanks for reporting this issue. I will try to fix this soon.
