### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by IRobL** [weakish/gister#22]
Would you be open to supporting HTTPS in addition to ssh for cloning?  Some networks disable ssh because they have problems with hackers git in through all the tunnels and stuff (or something, who knows!).

**Comment by weakish** [comment]
Yes, would be glad to see this.

**Comment by TheNotary** [comment]
I've been thinking about this, and I'm not sure how to best implement a key/ value configuration file in bash.  The easiest way might be to make a folder `~/.gister/` and put files for each of the settings we want in there.  I like using yaml a lot, but don't know how to set a value in yaml using bash.

**Comment by IRobL** [comment]
I've been thinking about this, and I'm not sure how to best implement a key/ value configuration file in bash. The easiest way might be to make a folder ~/.gister/ and put files for each of the settings we want in there. I like using yaml a lot, but don't know how to set a value in yaml using bash.

**Comment by weakish** [comment]
> I'm not sure how to best implement a key/ value configuration file in bash

I would delegate configuration option to git (probably in `[gister]` section). Read and write configuration option via invoking `git config`.

> ... in bash

Strictly speaking, `gister` is implemented in `sh`, not `bash`. It works under bash, zsh, dash, etc.

**Comment by IRobL** [comment]
Ah, I'm not very experienced with using `git config`.  I put together a PR, #24.  It dodges the need for a configuration file by simply looking to see if `GISTER_USE_HTTPS` is set to true.  If you can perform the feature better, feel free to close this issue/ PR, and thanks again for sharing this, it's working great!

**Comment by weakish** [comment]
I think using environment variables is fine.

**Comment by weakish** [comment]
closed in 8fd2782
