### ISSUE TITLE
How to use gitster init

### ISSUE THREAD

**Issue by Aletz-Arce** [weakish/gister#26]
After install runing gister init throw error with messages:
You need a github oauth2 token.
We need your username and password to get an OAuth2 token (with the "gist" permission).
We will not store your password.

Where or how  confugure thar Auth 2.0 token?

**Comment by weakish** [comment]
`gister init` will ask your username and password to get the token.
If you did not see an error,
probably you haven't install the [dependencies of gister].

If you have already installed the dependencies required, but still encountered error,
please provide the output of the following command:

```sh
gist --version
```

[dependencies of gister]: https://github.com/weakish/gister#dependencies
