### ISSUE TITLE
Non clear instructions for installation

### ISSUE THREAD

**Issue by tilakapash** [weakish/gister#27]
Hi,

I folllowed the installation steps and after make I run gister init 
`> gister init`

`You need a github oauth2 token.
We need your username and password to get an OAuth2 token (with the "gist" permission).
We will not store your password.
/usr/local/bin/gister: line 228: gist: command not found`

You don't explain how to get that github oauth2 token.

When I go on github it asks me for:

Application name
Something users will recognize and trust.
Homepage URL
The full URL to your application homepage.
Application description
Application description is optional
This is displayed to all users of your application.
Authorization callback URL

And if I get the Oauth token how do I insert it into gister ?

If you could explain the process step by step it would be appreciated ...

**Comment by weakish** [comment]
> /usr/local/bin/gister: line 228: gist: command not found

This error message indicates that you have not installed the dependency `gist` (gist.rb).
See: https://github.com/weakish/gister#dependencies
