### ISSUE TITLE
trying to run in a docker container; certificate verification failed; any suggestions

### ISSUE THREAD

**Issue by Freewilly3d** [weakish/gister#30]
I installed and updated the ca-certificates in my docker file.
I temporarily turned off ssl verication by adding this to my dockerfile ENV GIT_SSL_NO_VERIFY=1
unable to access 'https://gist.github.com/....git/': server certificate verification failed. CAfile: none CRLfile: none

[dockerfile.txt](https://github.com/weakish/gister/files/6217359/dockerfile.txt)

**Comment by weakish** [comment]
I have not tested it but I suspect that there is some issue with your container's time.

Certificate verification requires comparing the local time of the client (container system time) and the server (GitHub).
